import {
  AlertTriangle,
  Award,
  BarChart2,
  Bell,
  BookOpen,
  Building,
  Building2,
  Bus,
  Calendar,
  CalendarCheck,
  CalendarDays,
  CalendarX,
  ClipboardList,
  CreditCard,
  DollarSign,
  Download,
  FileText,
  FileQuestion,
  TicketCheck,
  GraduationCap,
  Hotel,
  LayoutGrid,
  Layers,
  ListChecks,
  ListTree,
  Megaphone,
  PieChart,
  Receipt,
  Shield,
  ShieldCheck,
  SlidersHorizontal,
  Sparkles,
  TrendingUp,
  User,
  UserCog,
  Users,
  Wallet,
  Inbox,
  Network,
  GitBranch,
  BookMarked,
  HeartHandshake,
  Scissors,
  Siren,
  Boxes,
  FileCheck2,
  Droplet,
  Ambulance,
  Utensils,
  Video,
  Share2,
  ScrollText,
  Activity,
  ShoppingCart,
  Store,
  NotebookPen,
  MapPin,
} from "lucide-react";
import type { ModuleDef } from "@/types/general/moduleConfig";

// Every page gets its own top-level tile on the dashboard — nothing hidden
// behind parent menus. Keep the grouping so the grid is still scannable.
export const BASE_MODULES: Omit<ModuleDef, "href">[] = [
  // ── People ────────────────────────────────────────────────────────
  { id: "admins",                 label: "Admins",               description: "Administrator accounts",         baseHref: "/admins",                 icon: Users,        color: "blue",   group: "People", roles: ["admin"] },
  { id: "employees",              label: "Employees",            description: "Staff profiles & departments", baseHref: "/employees",              icon: UserCog,      color: "blue",   group: "People", roles: ["admin", "staff"] },
  { id: "students",               label: "Students",             description: "Enrollment & records",         baseHref: "/students",               icon: GraduationCap, color: "blue",  group: "People", roles: ["admin", "teacher"] },
  { id: "organization-structure", label: "Org Structure",        description: "Hierarchy, departments, find people", baseHref: "/organization-structure", icon: Network,      color: "blue",   group: "People", roles: ["admin", "teacher", "staff"] },

  // ── Academics ─────────────────────────────────────────────────────
  { id: "marks",         label: "Marks",        description: "Grade entry & marksheets",     baseHref: "/marks",              icon: BookOpen,      color: "purple", group: "Academics", roles: ["admin", "teacher", "student"] },
  { id: "results",       label: "Results",      description: "Exam results & transcripts",   baseHref: "/results",            icon: Award,         color: "purple", group: "Academics", roles: ["admin", "teacher", "student"] },
  { id: "courses",       label: "Courses",      description: "Programmes & batches",         baseHref: "/academic/courses",   icon: GraduationCap, color: "purple", group: "Academics", roles: ["admin", "teacher"] },
  { id: "subjects",      label: "Subjects",     description: "Course subjects & syllabi",    baseHref: "/academic/subjects",  icon: ClipboardList, color: "purple", group: "Academics", roles: ["admin", "teacher"] },
  { id: "curriculum",    label: "Curriculum",   description: "Subjects per semester & year", baseHref: "/academic/curriculum", icon: ListTree, color: "purple", group: "Academics", roles: ["admin"] },
  { id: "grading",       label: "Grading",      description: "Grade scale, GPA & result rules", baseHref: "/academic/grading", icon: SlidersHorizontal, color: "purple", group: "Academics", roles: ["admin"] },
  { id: "exam-types",    label: "Exams",        description: "Assessment types per department", baseHref: "/academic/exam-types", icon: ListChecks, color: "purple", group: "Academics", roles: ["admin", "teacher"] },
  { id: "exams",         label: "Exam Schedules", description: "Plan & publish exam dates",  baseHref: "/academic/exams",     icon: Calendar,      color: "purple", group: "Academics", roles: ["admin", "teacher"] },
  { id: "assignments",   label: "Assignments",  description: "Set coursework & grade submissions", baseHref: "/academic/assignments", icon: NotebookPen, color: "purple", group: "Academics", roles: ["admin", "teacher"] },
  { id: "timetable",     label: "Timetable",    description: "Class & session schedules",    baseHref: "/timetable",          icon: LayoutGrid,    color: "purple", group: "Academics", roles: ["admin", "teacher", "student", "staff"] },

  // ── Exam Cell ─────────────────────────────────────────────────────
  { id: "question-bank",   label: "Question Bank",   description: "Reusable questions per subject",   baseHref: "/academic/question-bank",   icon: FileQuestion, color: "purple", group: "Exam Cell", roles: ["admin", "teacher"] },
  { id: "question-papers", label: "Question Papers", description: "Rule-based paper generation",      baseHref: "/academic/question-papers", icon: FileText,     color: "purple", group: "Exam Cell", roles: ["admin", "teacher"] },
  { id: "hall-tickets",    label: "Hall Tickets",    description: "Admit cards with verification QR", baseHref: "/academic/hall-tickets",    icon: TicketCheck,  color: "purple", group: "Exam Cell", roles: ["admin", "staff"] },

  // ── Operations ────────────────────────────────────────────────────
  { id: "attendance",          label: "Attendance",          description: "Mark & track attendance",     baseHref: "/attendance",          icon: CalendarCheck, color: "green", group: "Operations", roles: ["admin", "teacher", "staff", "student"] },
  { id: "attendance-summary",  label: "Attendance Summary",  description: "Aggregated attendance view",  baseHref: "/attendance/summary",  icon: BarChart2,     color: "green", group: "Operations", roles: ["admin", "teacher"] },
  { id: "attendance-shortage", label: "Shortage List",       description: "Students below threshold",    baseHref: "/attendance/shortage", icon: AlertTriangle, color: "green", group: "Operations", roles: ["admin"] },
  { id: "attendance-export",   label: "Attendance Export",   description: "Download attendance data",    baseHref: "/attendance/export",   icon: Download,      color: "green", group: "Operations", roles: ["admin"] },
  { id: "leaves",              label: "Leaves",              description: "Leave requests & approvals",  baseHref: "/leaves",              icon: FileText,      color: "green", group: "Operations", roles: ["admin", "teacher", "staff"] },
  { id: "leave-types",         label: "Leave Types",         description: "Configure leave categories",  baseHref: "/leave-types",         icon: FileText,      color: "green", group: "Operations", roles: ["admin"] },
  { id: "my-approvals",        label: "My Approvals",        description: "Requests waiting on you & yours", baseHref: "/my-approvals",    icon: Inbox,         color: "green", group: "Operations", roles: ["admin", "teacher", "staff"] },
  { id: "approval-flows",      label: "Approval Flows",      description: "Build multi-step approval chains", baseHref: "/approval-flows", icon: GitBranch,     color: "green", group: "Operations", roles: ["admin"] },
  { id: "approval-types",      label: "Approval Types",      description: "Define approval categories",  baseHref: "/approval-types",      icon: SlidersHorizontal, color: "green", group: "Operations", roles: ["admin"] },
  { id: "duty-roster",         label: "Duty Roster",         description: "Shift schedule for staff",    baseHref: "/hr/duty-roster",      icon: CalendarDays,      color: "green", group: "Operations", roles: ["admin", "staff"] },

  // ── Finance ───────────────────────────────────────────────────────
  { id: "payroll",            label: "Payroll",            description: "Salary & payroll processing",      baseHref: "/payroll",            icon: DollarSign,        color: "orange", group: "Finance", roles: ["admin", "teacher", "staff"] },
  { id: "salary-templates",   label: "Salary Templates",   description: "Reusable salary structures",       baseHref: "/salary/templates",   icon: SlidersHorizontal, color: "orange", group: "Finance", roles: ["admin"] },
  { id: "salary-assignments", label: "Salary Assignments", description: "Assign templates to employees",    baseHref: "/salary/assignment",  icon: Users,             color: "orange", group: "Finance", roles: ["admin"] },
  { id: "fees",               label: "Fees",               description: "Fee collection & records",         baseHref: "/fees/payments",      icon: CreditCard,        color: "orange", group: "Finance", roles: ["admin", "staff"] },
  { id: "fee-structures",     label: "Fee Structures",     description: "Define fee structures",            baseHref: "/fees/structures",    icon: Layers,            color: "orange", group: "Finance", roles: ["admin"] },
  { id: "fee-dues",           label: "Fee Dues",           description: "Outstanding fee dues",             baseHref: "/fees/dues",          icon: Wallet,            color: "orange", group: "Finance", roles: ["admin", "staff"] },
  { id: "fee-categories",     label: "Fee Categories",     description: "Category / head of account",       baseHref: "/fees/categories",    icon: Receipt,           color: "orange", group: "Finance", roles: ["admin"] },
  { id: "fee-addons",         label: "Fee Add-ons",        description: "Optional & one-off fee items",     baseHref: "/fees/addons",        icon: SlidersHorizontal, color: "orange", group: "Finance", roles: ["admin"] },
  { id: "fee-allocations",    label: "Fee Allocations",    description: "Assign structures to cohorts",     baseHref: "/fees/allocations",   icon: Layers,            color: "orange", group: "Finance", roles: ["admin"] },
  { id: "fee-students",       label: "Student Fees",       description: "Per-student fee ledger",           baseHref: "/fees/students",      icon: Wallet,            color: "orange", group: "Finance", roles: ["admin", "staff"] },
  { id: "fee-overview",       label: "Fee Overview",       description: "Collection summary",               baseHref: "/fees/overview",      icon: TrendingUp,        color: "orange", group: "Finance", roles: ["admin", "staff"] },
  { id: "chart-of-accounts",  label: "Chart of Accounts",  description: "Ledger accounts & journals",       baseHref: "/finance/chart-of-accounts", icon: ListTree,   color: "orange", group: "Finance", roles: ["admin"] },
  { id: "ledger",             label: "General Ledger",     description: "Journal entries & statements",     baseHref: "/finance/ledger",     icon: BookOpen,          color: "orange", group: "Finance", roles: ["admin"] },
  { id: "accounts-receivable", label: "Receivables",       description: "What's owed to you (aging)",       baseHref: "/finance/ar",         icon: TrendingUp,        color: "orange", group: "Finance", roles: ["admin"] },
  { id: "accounts-payable",   label: "Payables",           description: "What you owe vendors (aging)",     baseHref: "/finance/ap",         icon: Wallet,            color: "orange", group: "Finance", roles: ["admin"] },

  // ── Facilities ────────────────────────────────────────────────────
  // Configurable physical facilities. Wards & Beds (below, healthcare) shares
  // this group; item visibility is industry-filtered so each tenant sees only
  // the facilities relevant to it.
  { id: "hostel",    label: "Hostel",    description: "Room & hostel management",   baseHref: "/hostel",    icon: Hotel,    color: "teal", group: "Facilities", roles: ["admin", "staff"] },
  { id: "transport", label: "Transport", description: "Buses & route management",   baseHref: "/transport", icon: Bus,      color: "teal", group: "Facilities", roles: ["admin", "staff"] },
  { id: "library",   label: "Library",   description: "Books & library records",    baseHref: "/library",   icon: BookOpen, color: "teal", group: "Facilities", roles: ["admin", "teacher", "staff", "student"] },

  // ── Campus ────────────────────────────────────────────────────────
  { id: "mess",           label: "Mess & Canteen", description: "Menus, meal attendance & spend", baseHref: "/hostel/mess",   icon: Utensils, color: "teal", group: "Campus", roles: ["admin", "staff"] },
  { id: "transport-live", label: "Live Transport", description: "Vehicle tracking & driver attendance", baseHref: "/transport/live", icon: MapPin, color: "teal", group: "Campus", roles: ["admin", "staff"] },
  { id: "events",    label: "Events",    description: "Campus events & calendar",   baseHref: "/events",    icon: Calendar, color: "teal", group: "Campus", roles: ["admin", "teacher", "student", "staff"] },

  // ── Clinical (healthcare industry — see MODULE_INDUSTRIES in lib/access.ts) ──
  { id: "patients",     label: "Patients",     description: "Patient registry & records",       baseHref: "/patients",     icon: Users,         color: "red", group: "Clinical", roles: ["admin", "teacher", "staff"] },
  { id: "appointments", label: "Appointments", description: "Consultation bookings",            baseHref: "/appointments", icon: CalendarCheck, color: "red", group: "Clinical", roles: ["admin", "teacher", "staff"] },
  { id: "encounters",   label: "OPD Visits",   description: "Visit notes, vitals & prescriptions", baseHref: "/encounters", icon: ClipboardList, color: "red", group: "Clinical", roles: ["admin", "teacher", "staff"] },
  { id: "billing",      label: "Billing",      description: "Service catalog, invoices & payments", baseHref: "/billing",   icon: Receipt,       color: "red", group: "Clinical", roles: ["admin", "staff"] },
  { id: "pharmacy",     label: "Pharmacy",     description: "Drug stock & dispensing",              baseHref: "/pharmacy",  icon: Layers,        color: "red", group: "Clinical", roles: ["admin", "staff"] },
  { id: "schedules",    label: "Schedules",    description: "Clinician consulting hours",           baseHref: "/schedules", icon: CalendarDays,  color: "red", group: "Clinical", roles: ["admin", "staff"] },
  { id: "admissions",   label: "Admissions",   description: "Inpatient admit, transfer & discharge", baseHref: "/ipd",       icon: Building2,     color: "red", group: "Clinical", roles: ["admin", "teacher", "staff"] },
  { id: "wards",        label: "Wards & Beds", description: "Ward, bay & bed management",            baseHref: "/wards",     icon: Hotel,         color: "red", group: "Facilities", roles: ["admin", "staff"] },
  { id: "laboratory",   label: "Laboratory",   description: "Lab test catalog, orders & results",   baseHref: "/laboratory", icon: ClipboardList, color: "red", group: "Clinical", roles: ["admin", "teacher", "staff"] },
  { id: "radiology",    label: "Radiology",    description: "Imaging orders & reports",              baseHref: "/radiology", icon: BookMarked,    color: "red", group: "Clinical", roles: ["admin", "teacher", "staff"] },
  { id: "nursing",      label: "Nursing",      description: "Vitals & medication records",           baseHref: "/nursing",   icon: HeartHandshake, color: "red", group: "Clinical", roles: ["admin", "teacher", "staff"] },
  { id: "ot",           label: "OT Schedule",  description: "Operation theatre bookings",            baseHref: "/ot",        icon: Scissors,      color: "red", group: "Clinical", roles: ["admin", "teacher", "staff"] },
  { id: "triage",       label: "Triage",       description: "Emergency acuity board",                baseHref: "/triage",    icon: Siren,         color: "red", group: "Clinical", roles: ["admin", "teacher", "staff"] },
  { id: "bloodbank",    label: "Blood Bank",   description: "Blood unit stock & requests",           baseHref: "/bloodbank", icon: Droplet,       color: "red", group: "Clinical", roles: ["admin", "staff"] },
  { id: "ambulance",    label: "Ambulance",    description: "Fleet & dispatch trips",                baseHref: "/ambulance", icon: Ambulance,     color: "red", group: "Clinical", roles: ["admin", "staff"] },
  { id: "dietary",      label: "Dietary",      description: "Diet plans & meal service",             baseHref: "/dietary",   icon: Utensils,      color: "red", group: "Clinical", roles: ["admin", "teacher", "staff"] },
  { id: "telemedicine", label: "Telemedicine", description: "Remote video consultations",            baseHref: "/telemedicine", icon: Video,      color: "red", group: "Clinical", roles: ["admin", "teacher", "staff"] },
  { id: "referrals",    label: "Referrals",    description: "Outbound patient referrals",            baseHref: "/referrals", icon: Share2,        color: "red", group: "Clinical", roles: ["admin", "teacher", "staff"] },
  { id: "inventory",    label: "Inventory",    description: "Stores, consumables & reagents",        baseHref: "/inventory", icon: Boxes,         color: "red", group: "Clinical", roles: ["admin", "staff"] },
  { id: "claims",       label: "Claims",       description: "Insurance / TPA claim lifecycle",       baseHref: "/claims",    icon: FileCheck2,    color: "red", group: "Clinical", roles: ["admin", "staff"] },
  { id: "patient-portal", label: "My Health",  description: "Your appointments, results & care",     baseHref: "/my-health", icon: Activity,      color: "red", group: "My Workspace", roles: ["patient"] },
  { id: "my-schedule",  label: "My Schedule",  description: "Your consulting hours & booked patients", baseHref: "/my-schedule", icon: CalendarDays, color: "red", group: "My Workspace", roles: ["teacher", "staff"] },

  // ── Procurement (all industries) ──────────────────────────────────
  { id: "vendors",         label: "Vendors",         description: "Suppliers you buy from",             baseHref: "/org/vendors",              icon: Store,        color: "teal", group: "Procurement", roles: ["admin", "staff"] },
  { id: "purchase-orders", label: "Purchase Orders", description: "Order stock, receive & invoice",     baseHref: "/inventory/purchase-orders", icon: ShoppingCart, color: "teal", group: "Procurement", roles: ["admin", "staff"] },

  // ── Communications ───────────────────────────────────────────────
  { id: "announcements", label: "Notices",        description: "Announcements & notices", baseHref: "/announcements", icon: Megaphone, color: "pink", group: "Communications", roles: ["admin", "teacher", "student", "staff"] },
  { id: "notifications", label: "Notifications",  description: "System notifications",    baseHref: "/notifications", icon: Bell,      color: "pink", group: "Communications", roles: ["admin", "teacher", "student", "staff"] },

  // ── Learning ──────────────────────────────────────────────────────
  { id: "learning",             label: "Goal Library",        description: "Training goals & library",           baseHref: "/learning",             icon: Sparkles, color: "purple", group: "Learning", roles: ["admin"] },
  { id: "learning-assignments", label: "Learning Assignments", description: "Assign goals to employees",         baseHref: "/learning/assignments", icon: Users,    color: "purple", group: "Learning", roles: ["admin"] },
  { id: "my-learning",          label: "My Learning",         description: "Training goals assigned to you",     baseHref: "/learning/my-goals",    icon: Sparkles, color: "purple", group: "Learning", roles: ["admin", "teacher", "student", "staff"] },

  // ── Reports ───────────────────────────────────────────────────────
  { id: "reports-attendance", label: "Attendance Report", description: "Attendance analytics",    baseHref: "/reports/attendance", icon: BarChart2,  color: "indigo", group: "Reports", roles: ["admin"] },
  { id: "reports-marks",      label: "Marks Report",      description: "Marks & grades analytics", baseHref: "/reports/marks",     icon: PieChart,   color: "indigo", group: "Reports", roles: ["admin"] },
  { id: "reports-fees",       label: "Fee Report",        description: "Fee collection analytics", baseHref: "/reports/fees",      icon: TrendingUp, color: "indigo", group: "Reports", roles: ["admin"] },
  { id: "reports-payroll",    label: "Payroll Report",    description: "Payroll analytics",        baseHref: "/reports/payroll",   icon: TrendingUp, color: "indigo", group: "Reports", roles: ["admin"] },
  { id: "reports-leaves",     label: "Leave Report",      description: "Leave analytics",          baseHref: "/reports/leaves",    icon: BarChart2,  color: "indigo", group: "Reports", roles: ["admin"] },

  // ── Administration ───────────────────────────────────────────────
  { id: "org",            label: "Org Profile",     description: "Settings & configuration",     baseHref: "/org/profile",        icon: Building,     color: "indigo", group: "Administration", roles: ["admin"] },
  { id: "departments",    label: "Departments",     description: "Create & manage departments",  baseHref: "/org/departments",    icon: Building2,    color: "indigo", group: "Administration", roles: ["admin"] },
  { id: "academic-years", label: "Academic Years",  description: "Session / academic years",     baseHref: "/org/academic-years", icon: Calendar,     color: "indigo", group: "Administration", roles: ["admin"] },
  { id: "roles",          label: "Roles",           description: "Custom roles & permissions",   baseHref: "/org/roles",          icon: Shield,       color: "indigo", group: "Administration", roles: ["admin"] },
  { id: "access-control", label: "Access Control",  description: "Role page & action permissions", baseHref: "/org/access-control", icon: ShieldCheck,  color: "indigo", group: "Administration", roles: ["admin"] },
  { id: "audit",          label: "Audit Trail",     description: "Every write & login logged",   baseHref: "/audit",              icon: ScrollText,   color: "indigo", group: "Administration", roles: ["admin"] },
  { id: "holidays",       label: "Holidays",        description: "Holiday calendar entries",     baseHref: "/org/holidays",       icon: CalendarX,    color: "indigo", group: "Administration", roles: ["admin"] },
  { id: "calendar",       label: "Calendar",        description: "Working days & half days",     baseHref: "/calendar",           icon: CalendarDays, color: "indigo", group: "Administration", roles: ["admin", "super_admin"] },

  // ── My Workspace ─────────────────────────────────────────────────
  { id: "ask-peepalai", label: "Ask PeepalAI", description: "Ask questions about your data in plain language", baseHref: "/ask", icon: Sparkles, color: "purple", group: "My Workspace", roles: ["admin", "teacher", "student", "staff", "patient"] },
  { id: "portal",   label: "My Portal", description: "Student self-service portal",   baseHref: "/portal",       icon: PieChart, color: "blue",   group: "My Workspace", roles: ["student"] },
  { id: "my-fees",  label: "My Fees",   description: "Your fees, schedule & receipts", baseHref: "/portal/fees", icon: Receipt,  color: "orange", group: "My Workspace", roles: ["student"] },
  { id: "my-grades", label: "My Grades", description: "Your semester grades & transcript", baseHref: "/portal/grades", icon: Award, color: "purple", group: "My Workspace", roles: ["student"] },
  { id: "my-hall-tickets", label: "My Hall Tickets", description: "Download your exam admit cards", baseHref: "/portal/hall-tickets", icon: TicketCheck, color: "purple", group: "My Workspace", roles: ["student"] },
  { id: "my-assignments", label: "My Assignments", description: "Coursework set for your class", baseHref: "/portal/assignments", icon: NotebookPen, color: "purple", group: "My Workspace", roles: ["student"] },
  { id: "my-mess",  label: "Mess Menu", description: "This week's mess menu",       baseHref: "/portal/mess",  icon: Utensils, color: "teal",   group: "My Workspace", roles: ["student"] },
  { id: "profile", label: "My Profile", description: "View & edit your profile",   baseHref: "/profile", icon: User,     color: "blue", group: "My Workspace", roles: ["admin", "teacher", "student", "staff"] },
  { id: "docs",    label: "Docs",       description: "User guide & developer docs", baseHref: "/docs",    icon: BookMarked, color: "blue", group: "My Workspace", roles: ["admin", "teacher", "staff"] },
];

export const PATH_NAMES: Record<string, string> = {
  "/dashboard": "Home",
  "/admins": "Admins",
  "/employees": "Employees",
  "/students": "Students",
  "/attendance": "Attendance",
  "/attendance/summary": "Attendance Summary",
  "/attendance/shortage": "Shortage List",
  "/attendance/export": "Attendance Export",
  "/marks": "Marks",
  "/results": "Results",
  "/leaves": "Leaves",
  "/hr/duty-roster": "Duty Roster",
  "/events": "Events",
  "/calendar": "Calendar",
  "/portal": "My Portal",
  "/portal/fees": "My Fees",
  "/portal/grades": "My Grades",
  "/portal/hall-tickets": "My Hall Tickets",
  "/academic/question-bank": "Question Bank",
  "/academic/question-papers": "Question Papers",
  "/academic/hall-tickets": "Hall Tickets",
  "/profile": "My Profile",
  "/academic/courses": "Courses",
  "/fees/addons": "Fee Add-ons",
  "/fees/allocations": "Fee Allocations",
  "/fees/students": "Student Fees",
  "/fees/overview": "Fee Overview",
  "/academic/subjects": "Subjects",
  "/academic/curriculum": "Curriculum",
  "/academic/grading": "Grading",
  "/academic/exam-types": "Exams",
  "/academic/exams": "Exam Schedules",
  "/timetable": "Timetable",
  "/payroll": "Payroll",
  "/salary/templates": "Salary Templates",
  "/salary/assignment": "Salary Assignments",
  "/fees": "Fees",
  "/fees/payments": "Fees",
  "/fees/structures": "Fee Structures",
  "/fees/dues": "Fee Dues",
  "/fees/categories": "Fee Categories",
  "/reports/attendance": "Attendance Report",
  "/reports/marks": "Marks Report",
  "/reports/fees": "Fee Report",
  "/reports/payroll": "Payroll Report",
  "/reports/leaves": "Leave Report",
  "/hostel": "Hostel",
  "/hostel/mess": "Mess & Canteen",
  "/transport": "Transport",
  "/transport/live": "Live Transport",
  "/academic/assignments": "Assignments",
  "/portal/assignments": "My Assignments",
  "/portal/mess": "Mess Menu",
  "/patients": "Patients",
  "/appointments": "Appointments",
  "/encounters": "OPD Visits",
  "/billing": "Billing",
  "/pharmacy": "Pharmacy",
  "/schedules": "Clinician Schedules",
  "/ipd": "Admissions",
  "/wards": "Wards & Beds",
  "/laboratory": "Laboratory",
  "/radiology": "Radiology",
  "/nursing": "Nursing",
  "/ot": "OT Schedule",
  "/triage": "Triage",
  "/inventory": "Inventory",
  "/claims": "Claims",
  "/bloodbank": "Blood Bank",
  "/ambulance": "Ambulance",
  "/dietary": "Dietary",
  "/telemedicine": "Telemedicine",
  "/referrals": "Referrals",
  "/audit": "Audit Trail",
  "/ask": "Ask PeepalAI",
  "/my-health": "My Health",
  "/my-schedule": "My Schedule",
  "/library": "Library",
  "/announcements": "Announcements",
  "/notifications": "Notifications",
  "/org/profile": "Org Profile",
  "/org/departments": "Departments",
  "/org/academic-years": "Academic Years",
  "/org/roles": "Roles",
  "/org/access-control": "Access Control",
  "/org/holidays": "Holidays",
  "/leave-types": "Leave Types",
  "/learning": "Learning Goals",
  "/learning/assignments": "Learning Assignments",
  "/learning/my-goals": "My Learning",
  "/my-approvals": "My Approvals",
  "/approval-flows": "Approval Flows",
  "/approval-types": "Approval Types",
  "/organization-structure": "Org Structure",
  "/docs":         "Docs",
  "/docs/dev":     "Developer Docs",
  "/docs/users":   "User Guide",
};
