import apiClient from "@/api/client";

// Finance service — what stays REST after the GraphQL migration:
//   • payrollAPI.downloadPDF — binary payslip blob, cannot go through GraphQL
//   • feeAPI.* — fee schedule + receipt PDFs, generated on the backend

// Salary templates and salary assignments have been migrated to GraphQL:
//   • salaryTemplates query, createSalaryTemplate/updateSalaryTemplate/deleteSalaryTemplate mutations
//   • salaryAssignments query, assignSalaryTemplate/bulkAssignSalaryTemplate/
//     updateSalaryAssignment/deleteSalaryAssignment mutations

// Payroll — only the binary PDF download stays REST.
export const payrollAPI = {
  downloadPDF: (id: string) =>
    apiClient.get(`/payroll/${id}/pdf`, { responseType: "blob" }),
};

// Fee PDFs are generated by the backend and streamed as a download.
export const feeAPI = {
  // The caller's own full fee schedule.
  downloadSchedulePDF: () =>
    apiClient.get(`/fees/me/schedule/pdf`, { responseType: "blob" }),
  // All of the caller's paid receipts in one file (one per page).
  downloadAllReceiptsPDF: () =>
    apiClient.get(`/fees/me/receipts/pdf`, { responseType: "blob" }),
  // A single payment receipt by payment id.
  downloadReceiptPDF: (paymentId: string) =>
    apiClient.get(`/fees/payments/${paymentId}/receipt`, { responseType: "blob" }),
};
