// Package envfile writes the backend's .env. The backend reads configuration
// from environment variables only, so this file is the single source of truth
// for its runtime settings.
package envfile

import (
	"crypto/rand"
	"encoding/base64"
	"fmt"
	"os"
	"sort"
	"strings"
)

// Vars is an ordered-on-write set of environment values.
type Vars map[string]string

// Secret returns a URL-safe random string of n bytes of entropy.
func Secret(n int) string {
	b := make([]byte, n)
	if _, err := rand.Read(b); err != nil {
		panic("no entropy available: " + err.Error())
	}
	return base64.RawURLEncoding.EncodeToString(b)
}

// Write renders vars to path with 0600 permissions (it holds JWT and DB
// secrets) and preserves nothing from any previous file.
func Write(path string, vars Vars) error {
	keys := make([]string, 0, len(vars))
	for k := range vars {
		keys = append(keys, k)
	}
	sort.Strings(keys)

	var sb strings.Builder
	sb.WriteString("# Generated by the Peepal installer. Edited values survive\n")
	sb.WriteString("# updates; delete this file to have it regenerated.\n\n")
	for _, k := range keys {
		fmt.Fprintf(&sb, "%s=%s\n", k, vars[k])
	}
	return os.WriteFile(path, []byte(sb.String()), 0o600)
}

// Exists reports whether an env file is already present, so updates leave a
// customer's edited settings alone.
func Exists(path string) bool {
	st, err := os.Stat(path)
	return err == nil && st.Size() > 0
}

// Read parses a KEY=VALUE file back into a map, ignoring comments and blank
// lines. The agent uses it to inject the backend's settings as real
// environment variables rather than relying on the file being present.
func Read(path string) (Vars, error) {
	b, err := os.ReadFile(path)
	if err != nil {
		return nil, err
	}
	vars := Vars{}
	for _, line := range strings.Split(string(b), "\n") {
		line = strings.TrimSpace(line)
		if line == "" || strings.HasPrefix(line, "#") {
			continue
		}
		k, v, ok := strings.Cut(line, "=")
		if !ok {
			continue
		}
		vars[strings.TrimSpace(k)] = strings.Trim(strings.TrimSpace(v), `"`)
	}
	return vars, nil
}

// Slice renders the vars as the "KEY=VALUE" list exec.Cmd expects.
func (v Vars) Slice() []string {
	out := make([]string, 0, len(v))
	for k, val := range v {
		out = append(out, k+"="+val)
	}
	sort.Strings(out)
	return out
}
