import type { Terminology } from "./types";

export const corporateTerminology: Terminology = {
  organization: "Company",
  organization_plural: "Companies",
  member: "Employee",
  member_plural: "Employees",
  staff: "Manager",
  staff_plural: "Managers",
  department: "Team",
  department_plural: "Teams",
  course: "Training",
  course_plural: "Trainings",
  attendance: "Attendance",
  marks: "Reviews",
  leave: "Time Off",
  session: "Session",
  session_plural: "Sessions",
  cohort: "Cohort",
  cohort_plural: "Cohorts",
  term: "Quarter",
  term_plural: "Quarters",
  year: "Financial Year",
  role_staff: "Manager",
  role_staff_plural: "Managers",
  role_member: "Employee",
  role_member_plural: "Employees",
  role_support: "Support Staff",
  role_support_plural: "Support Staff",
};
