import type { Terminology } from "./types";

export const educationTerminology: Terminology = {
  organization: "Institute",
  organization_plural: "Institutes",
  member: "Student",
  member_plural: "Students",
  staff: "Teacher",
  staff_plural: "Teachers",
  department: "Department",
  department_plural: "Departments",
  course: "Course",
  course_plural: "Courses",
  attendance: "Attendance",
  marks: "Marks",
  leave: "Leave",
  session: "Class",
  session_plural: "Classes",
  cohort: "Batch",
  cohort_plural: "Batches",
  term: "Semester",
  term_plural: "Semesters",
  year: "Academic Year",
  role_staff: "Teacher",
  role_staff_plural: "Teachers",
  role_member: "Student",
  role_member_plural: "Students",
  role_support: "Staff",
  role_support_plural: "Staff",
};
