import type { Terminology } from "./types";

export const nonprofitTerminology: Terminology = {
  organization: "Organization",
  organization_plural: "Organizations",
  member: "Member",
  member_plural: "Members",
  staff: "Coordinator",
  staff_plural: "Coordinators",
  department: "Program",
  department_plural: "Programs",
  course: "Workshop",
  course_plural: "Workshops",
  attendance: "Participation",
  marks: "Milestones",
  leave: "Leave",
  session: "Session",
  session_plural: "Sessions",
  cohort: "Group",
  cohort_plural: "Groups",
  term: "Cycle",
  term_plural: "Cycles",
  year: "Program Year",
  role_staff: "Coordinator",
  role_staff_plural: "Coordinators",
  role_member: "Member",
  role_member_plural: "Members",
  role_support: "Volunteer",
  role_support_plural: "Volunteers",
};
